# Generated by Django 5.1.7 on 2025-03-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_paymentrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Популярные товары'),
        ),
    ]
